name: 'dbt_redlake'
version: '1.0'
profile: 'redlake'
data-paths: ["seeds"]

models:
  dbt_redlake:
    staging:
      materialized: table
    intermediate:
      materialized: table
    marts:
      materialized: table
