version: 2
models:
  - name: stg_reddit_posts
    description: "Cleaned and standardized Reddit posts"
    columns:
      - name: post_id
        tests: [unique, not_null]
      - name: score
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100000

  - name: stg_reddit_comments
    description: "Cleaned and standardized Reddit comments"
    columns:
      - name: comment_id
        tests: [unique, not_null]
      - name: score
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -10
              max_value: 10000
